version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: energy
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_pw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - energynet

volumes:
  postgres_data:

networks:
  energynet:
