spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: disysuser
    password: disyspw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  queue: energy.queue
  update-notification-queue: usage.updated.queue

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
