spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energy
    username: energy_user
    password: energy_pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
